# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import Flight_pb2 as Flight__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in Flight_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FlightServiceStub(object):
    """Flight service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Handshake = channel.stream_stream(
                '/arrow.flight.protocol.FlightService/Handshake',
                request_serializer=Flight__pb2.HandshakeRequest.SerializeToString,
                response_deserializer=Flight__pb2.HandshakeResponse.FromString,
                _registered_method=True)
        self.ListFlights = channel.unary_stream(
                '/arrow.flight.protocol.FlightService/ListFlights',
                request_serializer=Flight__pb2.Criteria.SerializeToString,
                response_deserializer=Flight__pb2.FlightInfo.FromString,
                _registered_method=True)
        self.GetFlightInfo = channel.unary_unary(
                '/arrow.flight.protocol.FlightService/GetFlightInfo',
                request_serializer=Flight__pb2.FlightDescriptor.SerializeToString,
                response_deserializer=Flight__pb2.FlightInfo.FromString,
                _registered_method=True)
        self.GetSchema = channel.unary_unary(
                '/arrow.flight.protocol.FlightService/GetSchema',
                request_serializer=Flight__pb2.FlightDescriptor.SerializeToString,
                response_deserializer=Flight__pb2.SchemaResult.FromString,
                _registered_method=True)
        self.DoGet = channel.unary_stream(
                '/arrow.flight.protocol.FlightService/DoGet',
                request_serializer=Flight__pb2.Ticket.SerializeToString,
                response_deserializer=Flight__pb2.FlightData.FromString,
                _registered_method=True)
        self.DoPut = channel.stream_stream(
                '/arrow.flight.protocol.FlightService/DoPut',
                request_serializer=Flight__pb2.FlightData.SerializeToString,
                response_deserializer=Flight__pb2.PutResult.FromString,
                _registered_method=True)
        self.DoExchange = channel.stream_stream(
                '/arrow.flight.protocol.FlightService/DoExchange',
                request_serializer=Flight__pb2.FlightData.SerializeToString,
                response_deserializer=Flight__pb2.FlightData.FromString,
                _registered_method=True)
        self.DoAction = channel.unary_stream(
                '/arrow.flight.protocol.FlightService/DoAction',
                request_serializer=Flight__pb2.Action.SerializeToString,
                response_deserializer=Flight__pb2.Result.FromString,
                _registered_method=True)
        self.ListActions = channel.unary_stream(
                '/arrow.flight.protocol.FlightService/ListActions',
                request_serializer=Flight__pb2.Empty.SerializeToString,
                response_deserializer=Flight__pb2.ActionType.FromString,
                _registered_method=True)


class FlightServiceServicer(object):
    """Flight service definition
    """

    def Handshake(self, request_iterator, context):
        """Handshake for auth
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFlights(self, request, context):
        """List available datasets
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFlightInfo(self, request, context):
        """Get metadata about a dataset
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSchema(self, request, context):
        """Get schema only
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DoGet(self, request, context):
        """Get data stream
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DoPut(self, request_iterator, context):
        """Send data stream
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DoExchange(self, request_iterator, context):
        """Bidirectional data exchange
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DoAction(self, request, context):
        """Execute action
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListActions(self, request, context):
        """List available actions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FlightServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Handshake': grpc.stream_stream_rpc_method_handler(
                    servicer.Handshake,
                    request_deserializer=Flight__pb2.HandshakeRequest.FromString,
                    response_serializer=Flight__pb2.HandshakeResponse.SerializeToString,
            ),
            'ListFlights': grpc.unary_stream_rpc_method_handler(
                    servicer.ListFlights,
                    request_deserializer=Flight__pb2.Criteria.FromString,
                    response_serializer=Flight__pb2.FlightInfo.SerializeToString,
            ),
            'GetFlightInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFlightInfo,
                    request_deserializer=Flight__pb2.FlightDescriptor.FromString,
                    response_serializer=Flight__pb2.FlightInfo.SerializeToString,
            ),
            'GetSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSchema,
                    request_deserializer=Flight__pb2.FlightDescriptor.FromString,
                    response_serializer=Flight__pb2.SchemaResult.SerializeToString,
            ),
            'DoGet': grpc.unary_stream_rpc_method_handler(
                    servicer.DoGet,
                    request_deserializer=Flight__pb2.Ticket.FromString,
                    response_serializer=Flight__pb2.FlightData.SerializeToString,
            ),
            'DoPut': grpc.stream_stream_rpc_method_handler(
                    servicer.DoPut,
                    request_deserializer=Flight__pb2.FlightData.FromString,
                    response_serializer=Flight__pb2.PutResult.SerializeToString,
            ),
            'DoExchange': grpc.stream_stream_rpc_method_handler(
                    servicer.DoExchange,
                    request_deserializer=Flight__pb2.FlightData.FromString,
                    response_serializer=Flight__pb2.FlightData.SerializeToString,
            ),
            'DoAction': grpc.unary_stream_rpc_method_handler(
                    servicer.DoAction,
                    request_deserializer=Flight__pb2.Action.FromString,
                    response_serializer=Flight__pb2.Result.SerializeToString,
            ),
            'ListActions': grpc.unary_stream_rpc_method_handler(
                    servicer.ListActions,
                    request_deserializer=Flight__pb2.Empty.FromString,
                    response_serializer=Flight__pb2.ActionType.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arrow.flight.protocol.FlightService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('arrow.flight.protocol.FlightService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FlightService(object):
    """Flight service definition
    """

    @staticmethod
    def Handshake(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/arrow.flight.protocol.FlightService/Handshake',
            Flight__pb2.HandshakeRequest.SerializeToString,
            Flight__pb2.HandshakeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFlights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/arrow.flight.protocol.FlightService/ListFlights',
            Flight__pb2.Criteria.SerializeToString,
            Flight__pb2.FlightInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFlightInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arrow.flight.protocol.FlightService/GetFlightInfo',
            Flight__pb2.FlightDescriptor.SerializeToString,
            Flight__pb2.FlightInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arrow.flight.protocol.FlightService/GetSchema',
            Flight__pb2.FlightDescriptor.SerializeToString,
            Flight__pb2.SchemaResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DoGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/arrow.flight.protocol.FlightService/DoGet',
            Flight__pb2.Ticket.SerializeToString,
            Flight__pb2.FlightData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DoPut(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/arrow.flight.protocol.FlightService/DoPut',
            Flight__pb2.FlightData.SerializeToString,
            Flight__pb2.PutResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DoExchange(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/arrow.flight.protocol.FlightService/DoExchange',
            Flight__pb2.FlightData.SerializeToString,
            Flight__pb2.FlightData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DoAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/arrow.flight.protocol.FlightService/DoAction',
            Flight__pb2.Action.SerializeToString,
            Flight__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListActions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/arrow.flight.protocol.FlightService/ListActions',
            Flight__pb2.Empty.SerializeToString,
            Flight__pb2.ActionType.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
